const Prolist = [
  {
    id: "1",
    img: "images/modamate-1.jpg",
    title: "Modeamate - Home 1",
    para: "Clothes and Fashion Shopify Theme",
    category: "modemate",
  },
  {
    id: "2",
    img: "images/modamate-2.jpg",
    title: "Modeamate - Home 2",
    para: "Clothes and Fashion Shopify Theme",
    category: "modemate",
  },
  {
    id: "3",
    img: "images/modamate-3.jpg",
    title: "Modeamate - Home 3",
    para: "Clothes and Fashion Shopify Theme",
    category: "modemate",
  },
  {
    id: "4",
    img: "images/modamate-4.jpg",
    title: "Modeamate - Home 4",
    para: "Clothes and Fashion Shopify Theme",
    category: "modemate",
  },
  {
    id: "5",
    img: "images/modamate-5.jpg",
    title: "Modeamate - Home 5",
    para: "Clothes and Fashion Shopify Theme",
    category: "modemate",
  },
  {
    id: "6",
    img: "images/modamate-6.jpg",
    title: "Modeamate - Home 6",
    para: "Clothes and Fashion Shopify Theme",
    category: "modemate",
  },
  {
    id: "7",
    img: "images/coolmate-1.jpg",
    title: "Coolmate- Home 1",
    para: "Clothes and Fashion Shopify Theme",
    category: "coolmate",
  },
  {
    id: "8",
    img: "images/coolmate-2.jpg",
    title: "Coolmate- Home 2",
    para: "Clothes and Fashion Shopify Theme",
    category: "coolmate",
  },
  {
    id: "9",
    img: "images/coolmate-3.jpg",
    title: "Coolmate- Home 3",
    para: "Clothes and Fashion Shopify Theme",
    category: "coolmate",
  },
  {
    id: "10",
    img: "images/coolmate-4.jpg",
    title: "Coolmate- Home 4",
    para: "Clothes and Fashion Shopify Theme",
    category: "coolmate",
  },
  {
    id: "11",
    img: "images/coolmate-5.jpg",
    title: "Coolmate- Home 5",
    para: "Clothes and Fashion Shopify Theme",
    category: "coolmate",
  },
  {
    id: "12",
    img: "images/coolmate-6.jpg",
    title: "Coolmate- Home 6",
    para: "Clothes and Fashion Shopify Theme",
    category: "coolmate",
  },
  {
    id: "13",
    img: "images/coolmate-7.jpg",
    title: "Coolmate- Home 7",
    para: "Clothes and Fashion Shopify Theme",
    category: "coolmate",
  },
  {
    id: "14",
    img: "images/coolmate-8.jpg",
    title: "Coolmate- Home 8",
    para: "Clothes and Fashion Shopify Theme",
    category: "coolmate",
  },
  {
    id: "15",
    img: "images/coolmate-9.jpg",
    title: "Coolmate- Home 9",
    para: "Clothes and Fashion Shopify Theme",
    category: "coolmate",
  },
  {
    id: "16",
    img: "images/coolmate-10.jpg",
    title: "Coolmate - Home 10",
    para: "Clothes and Fashion Shopify Theme",
    category: "coolmate",
  },
  {
    id: "17",
    img: "images/coolmate-11.jpg",
    title: "Coolmate - Home 11",
    para: "Clothes and Fashion Shopify Theme",
    category: "coolmate",
  },
  {
    id: "18",
    img: "images/coolmate-12.jpg",
    title: "Coolmate - Home 12",
    para: "Clothes and Fashion Shopify Theme",
    category: "coolmate",
  },
  {
    id: "19",
    img: "images/freshmate-1.jpg",
    title: "Freshmate - Home 11",
    para: "Clothes and Fashion Shopify Theme",
    category: "freshmate",
  },
  {
    id: "20",
    img: "images/freshmate-2.jpg",
    title: "Freshmate - Home 2",
    para: "Clothes and Fashion Shopify Theme",
    category: "freshmate",
  },
  {
    id: "21",
    img: "images/freshmate-3.jpg",
    title: "Freshmate - Home 3",
    para: "Clothes and Fashion Shopify Theme",
    category: "freshmate",
  },
  {
    id: "22",
    img: "images/petmate-1.jpg",
    title: "petmate - Home 1",
    para: "Clothes and Fashion Shopify Theme",
    category: "petmate",
  },
  {
    id: "23",
    img: "images/petmate-2.jpg",
    title: "petmate - Home 2",
    para: "Clothes and Fashion Shopify Theme",
    category: "petmate",
  },
  {
    id: "24",
    img: "images/petmate-3.jpg",
    title: "petmate - Home 3",
    para: "Clothes and Fashion Shopify Theme",
    category: "petmate",
  },
  {
    id: "25",
    img: "images/biomate-1.jpg",
    title: "Biomate - Home 1",
    para: "Clothes and Fashion Shopify Theme",
    category: "biomate",
  },
  {
    id: "26",
    img: "images/biomate-2.jpg",
    title: "Biomate - Home 2",
    para: "Clothes and Fashion Shopify Theme",
    category: "biomate",
  },
  {
    id: "27",
    img: "images/biomate-3.jpg",
    title: "Biomate - Home 3",
    para: "Clothes and Fashion Shopify Theme",
    category: "biomate",
  },
  {
    id: "28",
    img: "images/weedmate-1.jpg",
    title: "Weedmate - Home 1",
    para: "Clothes and Fashion Shopify Theme",
    category: "weedmate",
  },
  {
    id: "29",
    img: "images/weedmate-2.jpg",
    title: "Weedmate - Home 2",
    para: "Clothes and Fashion Shopify Theme",
    category: "weedmate",
  },
  {
    id: "30",
    img: "images/weedmate-3.jpg",
    title: "Weedmate - Home 3",
    para: "Clothes and Fashion Shopify Theme",
    category: "weedmate",
  },
  {
    id: "31",
    img: "images/weedmate-4.jpg",
    title: "Weedmate - Home 4",
    para: "Clothes and Fashion Shopify Theme",
    category: "weedmate",
  },
  {
    id: "32",
    img: "images/onemate-1.jpg",
    title: "Onemate - Home 1",
    para: "Clothes and Fashion Shopify Theme",
    category: "onemate",
  },
  {
    id: "33",
    img: "images/onemate-2.jpg",
    title: "Onemate - Home 2",
    para: "Clothes and Fashion Shopify Theme",
    category: "onemate",
  },
  {
    id: "34",
    img: "images/onemate-3.jpg",
    title: "Onemate - Home 3",
    para: "Clothes and Fashion Shopify Theme",
    category: "onemate",
  },
  {
    id: "35",
    img: "images/onemate-5.jpg",
    title: "Onemate - Home 4",
    para: "Clothes and Fashion Shopify Theme",
    category: "onemate",
  },
  {
    id: "36",
    img: "images/onemate-6.jpg",
    title: "Onemate - Home 5",
    para: "Clothes and Fashion Shopify Theme",
    category: "onemate",
  },
  {
    id: "37",
    img: "images/onemate-7.jpg",
    title: "Onemate - Home 6",
    para: "Clothes and Fashion Shopify Theme",
    category: "onemate",
  },
  {
    id: "38",
    img: "images/onemate-8.jpg",
    title: "Onemate - Home 7",
    para: "Clothes and Fashion Shopify Theme",
    category: "onemate",
  },
  {
    id: "39",
    img: "images/shoes-1.jpg",
    title: "Mate shoes - Home 1",
    para: "Clothes and Fashion Shopify Theme",
    category: "shoes",
  },
  {
    id: "40",
    img: "images/shoes-2.jpg",
    title: "Mate shoes - Home 2",
    para: "Clothes and Fashion Shopify Theme",
    category: "shoes",
  },
  {
    id: "41",
    img: "images/shoes-3.jpg",
    title: "Mate shoes - Home 3",
    para: "Clothes and Fashion Shopify Theme",
    category: "shoes",
  },
  {
    id: "42",
    img: "images/shoes-4.jpg",
    title: "Mate shoes - Home 4",
    para: "Clothes and Fashion Shopify Theme",
    category: "shoes",
  },
  {
    id: "43",
    img: "images/shoes-5.jpg",
    title: "Mate shoes - Home 5",
    para: "Clothes and Fashion Shopify Theme",
    category: "shoes",
  },
  {
    id: "44",
    img: "images/shoes-6.jpg",
    title: "Mate shoes - Home 6",
    para: "Clothes and Fashion Shopify Theme",
    category: "shoes",
  },
  {
    id: "46",
    img: "images/teemate-1.jpg",
    title: "Mate Tees - Home 1",
    para: "Clothes and Fashion Shopify Theme",
    category: "teemate",
  },
  {
    id: "47",
    img: "images/teemate-2.jpg",
    title: "Mate Tees - Home 2",
    para: "Clothes and Fashion Shopify Theme",
    category: "teemate",
  },
  {
    id: "48",
    img: "images/teemate-2.jpg",
    title: "Mate Tees - Home 2",
    para: "Clothes and Fashion Shopify Theme",
    category: "teemate",
  },
  {
    id: "49",
    img: "images/digimate-1.jpg",
    title: "DigiMate - Home 1",
    para: "Clothes and Fashion Shopify Theme",
    category: "digimate",
  },
  {
    id: "50",
    img: "images/digimate-2.jpg",
    title: "DigiMate - Home 2",
    para: "Clothes and Fashion Shopify Theme",
    category: "digimate",
  },
  {
    id: "51",
    img: "images/digimate-3.jpg",
    title: "DigiMate - Home 3",
    para: "Clothes and Fashion Shopify Theme",
    category: "digimate",
  },
  {
    id: "52",
    img: "images/playmate-1.jpg",
    title: "PlayMate - Home 1",
    para: "Clothes and Fashion Shopify Theme",
    category: "playmate",
  },
  {
    id: "53",
    img: "images/playmate-2.jpg",
    title: "PlayMate - Home 2",
    para: "Clothes and Fashion Shopify Theme",
    category: "playmate",
  },
  {
    id: "54",
    img: "images/playmate-3.jpg",
    title: "PlayMate - Home 3",
    para: "Clothes and Fashion Shopify Theme",
    category: "playmate",
  },
  {
    id: "55",
    img: "images/playmate-4.jpg",
    title: "PlayMate - Home 4",
    para: "Clothes and Fashion Shopify Theme",
    category: "playmate",
  },
];

export default Prolist;
